name: PR lint

on:
    pull_request:
        types: [opened, edited, reopened, synchronize]

jobs:
    semantic-pr:
        runs-on: ubuntu-latest
        steps:
            - name: Validate PR title & body (semantic)
              uses: amannn/action-semantic-pull-request@v4
              with:
                  title-regex: '^(feat|fix|docs|style|refactor|perf|test|chore)(\([^)]+\))?!?:\s.+'
                  body-required: true
                  body-min-length: 20
